package org.telegram.bot;

/**
 * Created by ex3ndr on 17.01.14.
 */
public class WarAndPeace {
    public static final String TEXT = "В Лысых Горах, имении князя Николая Андреевича Болконского, ожидали с каждым днем приезда молодого князя Андрея с княгиней; но ожидание не нарушило стройного порядка, по которому шла жизнь в доме старого князя. Генерал-аншеф князь Николай Андреевич, по прозванию в обществе le roi de Prusse 1, — с того времени, как при Павле был сослан в деревню, жил безвыездно в своих Лысых Горах с дочерью, княжною Марьей, и при ней компаньонкой, m-lle Bourienne 2. И в новое царствование, хотя ему и был разрешен въезд в столицы, он также продолжал безвыездно жить в деревне, говоря, что ежели кому его нужно, то тот и от Москвы полтораста верст доедет до Лысых Гор, а что ему никого и ничего не нужно. Он говорил, что есть только два источника людских пороков: праздность и суеверие, и что есть только две добродетели: деятельность и ум. Он сам занимался воспитанием своей дочери и, чтобы развить в ней обе главные добродетели, давал ей уроки алгебры и геометрии и распределял всю ее жизнь в беспрерывных занятиях. Сам он постоянно был занят то писанием своих мемуаров, то выкладками из высшей математики, то точением табакерок на станке, то работой в саду и наблюдением над постройками, которые не прекращались в его имении. Так как главное условие для деятельности есть порядок, то и порядок в его образе жизни был доведен до последней степени точности. Его выходы к столу совершались при одних и тех же неизменных условиях, и не только в один и тот же час, но и минуту. С людьми, окружавшими его, от дочери до слуг, князь был резок и неизменно требователен, и потому, не быв жестоким, он возбуждал к себе страх и почтительность, каких не легко мог бы добиться самый жестокий человек. Несмотря на то, что он был в отставке и не имел теперь никакого значения в государственных делах, каждый начальник той губернии, где было имение князя, считал своим долгом являться к нему и точно так же, как архитектор, садовник или княжна Марья, дожидался назначенного часа выхода князя в высокой официантской. И каждый в этой официантской испытывал то же чувство почтительности и даже страха, в то время как отворялась громадно-высокая дверь кабинета и показывалась в напудренном парике невысокая фигурка старика с маленькими сухими ручками и серыми висячими бровями, иногда, как он насупливался, застилавшими блеск умных и молодых блестящих глаз.\n" +
            "В день приезда молодых, утром, по обыкновению, княжна Марья в урочный час входила для утреннего приветствия в официантскую и со страхом крестилась и читала внутренно молитву. Каждый день она входила и каждый день молилась о том, чтоб это ежедневное свидание сошло благополучно.\n" +
            "Сидевший в официантской пудреный старик слуга тихим движением встал и шепотом доложил: «Пожалуйте».\n" +
            "Из-за двери слышались равномерные звуки станка. Княжна робко потянула за легко и плавно отворяющуюся дверь и остановилась у входа. Князь работал за станком и, оглянувшись, продолжал свое дело.\n" +
            "Огромный кабинет был наполнен вещами, очевидно, беспрестанно употребляемыми. Большой стол, на котором лежали книги и планы, высокие стеклянные шкафы библиотеки с ключами в дверцах, высокий стол для писания в стоячем положении, на котором лежала открытая тетрадь, токарный станок, с разложенными инструментами и с рассыпанными кругом стружками, — все выказывало постоянную, разнообразную и порядочную деятельность. По движениям небольшой ноги, обутой в татарский, шитый серебром, сапожок, по твердому налеганию жилистой, сухощавой руки видна была в князе еще упорная и много выдерживающая сила свежей старости. Сделав несколько кругов, он снял ногу с педали станка, обтер стамеску, кинул ее в кожаный карман, приделанный к станку, и, подойдя к столу, подозвал дочь. Он никогда не благословлял своих детей и только, подставив ей щетинистую, еще не бритую нынче щеку, сказал, строго и вместе с тем внимательно-нежно оглядев ее:\n" +
            "— Здорова?.. ну, так садись!\n" +
            "Он взял тетрадь геометрии, писанную его рукой, и подвинул ногой свое кресло.\n" +
            "— На завтра! — сказал он, быстро отыскивая страницу и от параграфа до другого отмечая жестким ногтем.\n" +
            "Княжна пригнулась к столу над тетрадью.\n" +
            "— Постой, письмо тебе, — вдруг сказал старик, доставая из приделанного над столом кармана конверт, надписанный женскою рукой, и кидая его на стол.\n" +
            "Лицо княжны покрылось красными пятнами при виде письма. Она торопливо взяла его и пригнулась к нему.\n" +
            "— От Элоизы? — спросил князь, холодною улыбкой выказывая еще крепкие и желтоватые зубы.\n" +
            "— Да, от Жюли, — сказала княжна, робко взглядывая и робко улыбаясь.\n" +
            "— Еще два письма пропущу, а третье прочту, — строго сказал князь, — боюсь, много вздору пишете. Третье прочту.\n" +
            "— Прочтите хоть это, mon père 3, — отвечала княжна, краснея еще более и подавая ему письмо.\n" +
            "— Третье, я сказал, третье, — коротко крикнул князь, отталкивая письмо, и, облокотившись на стол, пододвинул тетрадь с чертежами геометрии.\n" +
            "— Ну, сударыня, — начал старик, пригнувшись близко к дочери над тетрадью и положив одну руку на спинку кресла, на котором сидела княжна, так что княжна чувствовала себя со всех сторон окруженною тем табачным и старчески-едким запахом отца, который она так давно знала. — Ну, сударыня, треугольники эти подобны; изволишь видеть, угол abc...\n" +
            "Княжна испуганно взглядывала на близко от нее блестящие глаза отца; красные пятна переливались по ее лицу, и видно было, что она ничего не понимает и так боится, что страх помешает ей понять все дальнейшие толкования отца, как бы ясны они ни были. Виноват ли был учитель, или виновата была ученица, но каждый день повторялось одно и то же: у княжны мутилось в глазах, она ничего не видела, не слышала, только чувствовала его дыхание и запах и только думала о том, как бы ей уйти поскорее из кабинета и у себя на просторе понять задачу. Старик выходил из себя: с грохотом отодвигал и придвигал кресло, на котором сам сидел, делал усилия над собой, чтобы не разгорячиться, и почти всякий раз горячился, бранился, а иногда швырял тетрадью.\n" +
            "Княжна ошиблась ответом.\n" +
            "— Ну, как же не дура! — крикнул князь, оттолкнув тетрадь и быстро отвернувшись, но тотчас же встал, прошелся, дотронулся руками до волос княжны и снова сел.\n" +
            "Он придвинулся и продолжал толкование.\n" +
            "— Нельзя, княжна, нельзя, — сказал он, когда княжна, взяв и закрыв тетрадь с заданными уроками, уже готовилась уходить, — математика великое дело, моя сударыня. А чтобы ты была похожа на наших глупых барынь, я не хочу. Стерпится — слюбится. — Он потрепал ее рукой по щеке. — Дурь из головы выскочит.\n" +
            "Она хотела выйти, он остановил ее жестом и достал с высокого стола новую, неразрезанную книгу.\n" +
            "— Вот еще какой-то Ключ таинства тебе твоя Элоиза посылает. Религиозная. А я ни в чью веру не вмешиваюсь... Просмотрел. Возьми. Ну, ступай, ступай!\n" +
            "Он потрепал ее по плечу и сам запер за нею дверь.\n" +
            "Княжна Марья возвратилась в свою комнату с грустным, испуганным выражением, которое редко покидало ее и делало ее некрасивое, болезненное лицо еще более некрасивым, села за свой письменный стол, уставленный миниатюрными портретами и заваленный тетрадями и книгами. Княжна была столь же беспорядочна, как отец ее порядочен. Она положила тетрадь геометрии и нетерпеливо распечатала письмо. Письмо было от ближайшего с детства друга княжны; друг этот был та самая Жюли Карагина, которая была на именинах у Ростовых.\n" +
            "Жюли писала:\n" +
            "«Chère et excellente amie, quelle chose terrible et effrayante que l'absence! J'ai beau me dire que la moitié de mon existence et de mon bonheur est en vous, que malgré la distance qui nous sépare, nos coeurs sont unis par des liens indissolubles; le mien se révolte contre la destinée, et je ne puis, malgré les plaisirs et les distractions qui m'entourent, vaincre une certaine tristesse cachée que je ressens au fond du cur depuis notre séparation. Pourquoi ne sommes-nous pas réunies, comme cet été dans votre grand cabinet sur le canapé bleu, le canapé à confidences? Pourquoi ne puis-je, comme il y a trois mois, puiser de nouvelles forces morales dans votre regard si doux, si calme et si pénétrant, regard que j'aimais tant et que je crois voir devant moi, quand je vous écris?» 4\n" +
            "Прочтя до этого места, княжна Марья вздохнула и оглянулась в трюмо, которое стояло направо от нее. Зеркало отразило некрасивое, слабое тело и худое лицо. Глаза, всегда грустные, теперь особенно безнадежно смотрели на себя в зеркало. «Она мне льстит», — подумала княжна, отвернулась и продолжала читать. Жюли, однако, не льстила своему другу: действительно, глаза княжны, большие, глубокие и лучистые (как будто лучи теплого света иногда снопами выходили из них), были так хороши, что очень часто, несмотря на некрасивость всего лица, глаза эти делались привлекательнее красоты. Но княжна никогда не видела хорошего выражения своих глаз, того выражения, которое они принимали в те минуты, когда она не думала о себе. Как и у всех людей, лицо ее принимало натянуто-неестественное, дурное выражение, как скоро она смотрелась в зеркало. Она продолжала читать:\n" +
            "«Tout Moscou ne parle que guerre. L'un de mes deux frères est déjà à l'étranger, l'autre est avec la garde qui se met en marche vers la frontière. Notre cher empereur a quitté Pétersbourg et, à ce qu'on prétend, compte lui-même exposer sa précieuse existence aux chances de la guerre. Dieu veuille que le monstre corsicain, qui détruit le repos de l'Europe, soit terrassé par l'ange que le Tout-Puissant, dans sa miséricorde, nous a donné pour souverain. Sans parler de mes frères, cette guerre m'a privée d'une relation des plus chères à mon cur. Je pane du jeune Nicolas Rostoff qui avec son enthousiasme n'a pu supporter l'inaction et a quitté l'université pour aller s'enrôler dans l'armée. Eh bien, chère Marie, je vous avouerai, que, malgré son extrême jeunesse, son départ pour l'armée a été un grand chagrin pour moi. Le jeune homme, dont je vous parlais cet été, a tant de noblesse, de véritable jeunesse qu'on rencontre si rarement dans le siècle où nous vivons parmi nos vieillards de vingt ans. Il a surtout tant de franchise et de cur. Il est tellement pur et poétique, que mes relations avec lui, quelques passagères qu'elles fussent, ont été l'une des plus douces jouissances de mon pauvre cur, qui a déjà tant souffert. Je vous raconterai un jour nos adieux et tout ce qui s'est dit en partant. Tout cela est encore trop frais. Ah! chère amie, vous êtes heureuse de ne pas connaître ces jouissances et ces peines si poignantes. Vous êtes heureuse, puisque les dernières sont ordinairement les plus fortes! Je sais fort bien que le comte Nicolas est trop jeune pour pouvoir jamais devenir pour moi quelque chose de plus qu'un ami, mais cette douce amitié, ces relations si poétiques et si pures ont été un besoin pour mon cur. Mais n'en parlons plus. La grande nouvelle du jour qui occupe tout Moscou est la mort du vieux comte Безухов et son héritage. Figurez-vous que les trois princesses n'ont reçu que très peu de chose, le prince Basile rien, et que c'est M. Pierre qui a tout hérité, et qui par-dessus le marché a été reconnu pour fils légitime, par conséquent comte Безухов est possesseur de la plus belle fortune de la Russie. On prétend que le prince Basile a joué un très vilain rôle dans toute cette histoire et qu'il est reparti tout penaud pour Pétersbourg.\n" +
            "Je vous avoue que je comprends très peu toutes ces affaires de legs et de testament; ce que je sais, c'est que depuis que le jeune homme que nous connaissions tous sous le nom de M. Pierre tout court est devenu comte Безухов et possesseur de l'une des plus grandes fortunes de la Russie, je m'amuse fort à observer les changements de ton et des manières des mamans accablées de filles à marier et des demoiselles elles-mêmes à l'égard de cet individu qui, par parenthèse, m'a paru toujours être un pauvre sire. Comme on s'amuse depuis deux ans à me donner des promis que je ne connais pas le plus souvent, la chronique matrimoniale de Moscou me fait comtesse Безуховой. Mais vous sentez bien que je ne me soucie nullement de le devenir. A propos de mariage, savez-vous que tout dernièrement la tante en général Анна Михайловна m'a confié sous le sceau du plus grand secret un projet de mariage pour vous. Ce n'est ni plus ni moins que le fils du prince Basile, Anatole, qu'on voudrait ranger en le mariant à une personne riche et distinguée, et c'est sur vous qu'est tombé le choix des parents. Je ne sais comment vous envisagerez la chose, mais j'ai cru de mon devoir de vous en avertir. On le dit très beau et très mauvais sujet; c'est tout ce que j'ai pu savoir sur son compte.\n" +
            "Mais assez de bavardage comme cela. Je finis mon second feuillet, et maman me fait chercher pour aller dîner chez les Apraksines. Lisez le livre mystique que je vous envoie et qui fait fureur chez nous. Quoiqu'il y ait des choses dans ce livre difficiles à atteindre avec la faible conception humaine, c'est un livre admirable dont la lecture calme et élève l'âme. Adieu. Mes respects à monsieur votre père et mes compliments à m-lle Bourienne. Je vous embrasse comme je vous aime.\n" +
            "Julie.\n" +
            "P.S. Donnez-moi des nouvelles de votre frère et de sa charmante petite femme» 5.\n" +
            "Княжна подумала, задумчиво улыбнулась (причем лицо ее, освещенное лучистыми глазами, совершенно преобразилось) и, вдруг приподнявшись, тяжело ступая, перешла к столу. Она достала бумагу, и рука ее быстро начала ходить по ней. Так писала она в ответ:\n" +
            "«Chère et excellente amie. Votre lettre du 13 m'a causé une grande joie. Vous m'aimez donc toujours, ma poétique Julie. L'absence dont vous dites tant de mal, n'a donc pas eu son influence habituelle sur vous. Vous vous plaignez de l'absence — que devrai-je dire moi si j'osais me plaindre, privée de tous ceux qui me sont chers? Ah! si nous n'avions pas la religion pour nous consoler, la vie serait bien triste. Pourquoi me supposez-vous un regard sévère quand vous me partez de votre affection pour le jeune homme? Sous ce rapport je ne suis rigide que pour moi. Je comprends ces sentiments chez les autres et si je ne puis approuver ne les ayant jamais ressentis, je ne les condamne pas. Il me paraît seulement que l'amour chrétien, l'amour du prochain, l'amour pour ses ennemis est plus méritoire, plus doux et plus beau, que ne le sont les sentiments que peuvent inspirer les beaux yeux d'un jeune homme à une jeune fille poétique et aimante comme vous.\n" +
            "La nouvelle de la mort du comte Безухов nous est par-venue avant votre lettre, et mon père en a été très affecté. Il dit que c'était l'avant-dernier représentant du grand siècle, et qu'à présent c'est son tour; mais qu'il fera son possible pour que son tour vienne le plus tard possible. Que Dieu nous garde de ce terrible malheur! Je ne puis partager votre opinion sur Pierre que j'ai connu enfant. Il me paraissait toujours avoir un cur excellent, et c'est la qualité que j'estime le plus dans les gens. Quant à son héritage et au rôle qu'y a joué le prince Basile, c'est bien triste pour tous les deux. Ah! chère amie, la parole de Notre Divin Sauveur qu'il est plus aisé à un chameau de passer par le trou d'une aiguille, qu'il ne l'est à un riche d'entrer dans le royaume de Dieu, cette parole est terriblement vraie; je plains le prince Basile et je regrette encore davantage Pierre. Si jeune et accablé de cette richesse, que de tentations n'aura-t-il pas à subir! Si on me demandait ce que je désirerais le plus au monde, ce serait d'être plus pauvre que le plus pauvre des mendiants. Mille grâces, chère amie, pour l'ouvrage que vous m'envoyez, et qui fait si grande fureur chez vous. Cependant, puisque vous me dites qu'au milieu de plusieurs bonnes choses il y en a d'autres que la faible conception humaine ne peut atteindre, il me paraît assez inutile de s'occuper d'une lecture inintelligible qui par là même ne pourrait être d'aucun fruit. Je n'ai jamais pu comprendre la passion qu'ont certaines personnes de s'embrouiller l'entendement en s'attachant à des livres mystiques, qui n'élèvent que des doutes dans leurs esprits, exaltent leur imagination et leur donnent un caractère d'exagération tout à fait contraire à la simplicité chrétienne. Lisons les apôtres et l'Evangile. Ne cherchons pas à pénétrer ce que ceux-là renferment de mystérieux, car comment oserions-nous, misérables pécheurs que nous sommes, prétendre à nous initier dans les secrets terribles et sacrés de la providence, tant que nous portons cette dépouille charnelle, qui élève entre nous et l'éternel un voile impénétrable? Bornons-nous donc à étudier les principes sublimes que Notre Divin Sauveur nous a laissé pour notre conduite ici-bas; cherchons à nous y conformer et à les suivre, persuadons-nous que moins nous donnons d'essor à notre faible esprit humain et plus il est agréable à Dieu, qui rejette toute science ne venant pas de lui; que moins nous cherchons à approfondir ce qu'il lui a plu de dérober à notre connaissance, et plutôt il nous en accordera la découverte par son divin esprit.\n" +
            "Mon père ne m'a pas parlé du prétendant, mais il m'a dit seulement qu'il a reçu une lettre et attendait une visite du prince Basile. Pour ce qui est du projet de mariage qui me regarde, je vous dirai, chère et excellente amie, que le mariage selon moi, est une institution divine à laquelle il faut se conformer. Quelque pénible que cela soit pour moi, si le Tout-Puissant m'impose jamais les devoirs d'épouse et de mère, je tâcherai de les remplir aussi fidèlement que je le pourrai, sans m'inquiéter de l'examen de mes sentiments à l'égard de celui qu'il me donnera pour époux.\n" +
            "J'ai reçu une lettre de mon frère qui m'annonce son arrivée à Лысые Горы avec sa femme. Ce sera une joie de courte durée, puisqu'il nous quitte pour prendre part à cette malheureuse guerre, à laquelle nous sommes entraînés Dieu sait comment et pourquoi. Non seulement chez vous, au centre des affaires et du monde, on ne parle que de guerre, mais ici, au milieu de ces travaux champêtres et de ce calme de la nature que les citadins se représentent ordinairement à la campagne, les bruits de la guerre se font entendre et sentir péniblement. Mon père ne parle que marche et contremarche, choses auxquelles je ne comprends rien; et avant-hier en faisant ma promenade habituelle dans la rue du village, je fus témoin d'une scène déchirante... C'était un convoi des recrues enrôlés chez nous et expédiés pour l'armée. Il fallait voir l'état dans lequel se trouvaient les mères, les femmes, les enfants des hommes qui partaient et entendre les sanglots des uns et des autres! On dirait que l'humanité à oublié les lois de Son Divin Sauveur qui prêchait l'amour et le pardon des offenses, et qu'elle fait consister son plus grand mérite dans l'art de s'entre-tuer.\n" +
            "Adieu, chère et bonne amie, que Notre Divin Sauveur et sa très Sainte Mère vous aient en leur sainte et puissante garde.\n" +
            "Marie» 6\n" +
            "— Ah, vous expédiez le courrier, princesse, moi j'ai déjà expédié le mien. J'ai écris à ma pauvre mère 7, — заговорила быстро-приятным, сочным голоском улыбающаяся m-lle Bourienne, картавя на р и внося с собой в сосредоточенную, грустную и пасмурную атмосферу княжны Марьи совсем другой, легкомысленно-веселый и самодовольный мир.\n" +
            "— Princesse, il faut que je vous prévienne, — прибавила она, понижая голос, — le prince a eu une altercation, — altercation, — сказала она, особенно грассируя и с удовольствием слушая себя, — une altercation avec Michel Ivanoff. Il est de très mauvaise humeur, très morose. Soyez prévenue, vous savez... 8\n" +
            "— Ah! chère amie, — отвечала княжна Марья, — je vous ai priée de ne jamais me prévenir de l'humeur dans laquelle se trouve mon père. Je ne me permets pas de le juger, et je ne voudrais pas que les autres le fassent 9.\n" +
            "Княжна взглянула на часы и, заметив, что она уже пять минут пропустила то время, которое должна была употреблять для игры на клавикордах, с испуганным видом пошла в диванную. Между двенадцатью и двумя часами, сообразно с заведенным порядком дня, князь отдыхал, а княжна играла на клавикордах.";

    public static final String TEXT2 = "Раздвинули бостонные столы, составились партии, и гости графа разместились в двух гостиных, диванной и библиотеке.\n" +
            "Граф, распустив карты веером, с трудом удерживался от привычки послеобеденного сна и всему смеялся. Молодежь, подстрекаемая графиней, собралась около клавикорд и арфы. Жюли первая, по просьбе всех, сыграла на арфе пиеску с вариациями и вместе с другими девицами стала просить Наташу и Николая, известных своею музыкальностью, спеть что-нибудь. Наташа, к которой обратились, как в большой, была, видимо, этим очень горда, но вместе с тем и робела.\n" +
            "— Что будем петь? — спросила она.\n" +
            "— «Ключ», — отвечал Николай.\n" +
            "— Ну, давайте скорее. Борис, идите сюда, — сказала Наташа. — А где же Соня?\n" +
            "Она оглянулась и, увидав, что ее друга нет в комнате, побежала за ней.\n" +
            "Вбежав в Сонину комнату и не найдя там своей подруги, Наташа пробежала в детскую — и там не было Сони. Наташа поняла, что Соня была в коридоре на сундуке. Сундук в коридоре был место печалей женского молодого поколения дома Ростовых. Действительно, Соня в своем воздушном розовом платьице, приминая его, лежала ничком на грязной полосатой няниной перине, на сундуке и, закрыв лицо пальчиками, навзрыд плакала, подрагивая своими оголенными плечиками. Лицо Наташи, оживленное, целый день именинное, вдруг изменилось: глаза ее остановились, потом содрогнулась ее широкая шея, углы губ опустились.\n" +
            "— Соня! что ты?.. Что, что с тобой? У-у-у!..\n" +
            "И Наташа, распустив свой большой рот и сделавшись совершенно дурною, заревела, как ребенок, не зная причины и только оттого, что Соня плакала. Соня хотела поднять голову, хотела отвечать, но не могла и еще больше спряталась. Наташа плакала, присев на синей перине и обнимая друга. Собравшись с силами, Соня приподнялась, начала утирать слезы и рассказывать.\n" +
            "— Николенька едет через неделю, его... бумага... вышла... он сам мне сказал... Да я бы все не плакала (она показала бумажку, которую держала в руке: то были стихи, написанные Николаем)... я бы все не плакала, но ты не можешь... никто не может понять... какая у него душа.\n" +
            "И она опять принялась плакать о том, что душа его была так хороша.\n" +
            "— Тебе хорошо... я не завидую... я тебя люблю, и Бориса тоже, — говорила она, собравшись немного с силами, — он милый... для вас нет препятствий. А Николай мне cousin... надобно... сам митрополит... и то нельзя. И потом, ежели маменьке (Соня графиню и считала и называла матерью)... она скажет, что я порчу карьеру Николая, у меня нет сердца, что я неблагодарная, а право... вот ей-богу (она перекрестилась)... я так люблю и ее и всех вас, только Вера одна... За что? Что я ей сделала? Я так благодарна вам, что рада бы всем пожертвовать, да мне нечем...\n" +
            "Соня не могла больше говорить и опять спрятала голову в руках и перине. Наташа начинала успокоиваться, но по лицу ее видно было, что она понимала всю важность горя своего друга.\n" +
            "— Соня! — сказала она вдруг, как будто догадавшись о настоящей причине огорчения кузины. — Верно, Вера с тобой говорила после обеда? Да?\n" +
            "— Да, эти стихи сам Николай написал, а я списала еще другие; она и нашла их у меня на столе и сказала, что покажет их маменьке, и еще говорила, что я неблагодарная, что маменька никогда не позволит ему жениться на мне, а он женится на Жюли. Ты видишь, как он с ней целый день... Наташа! За что?..\n" +
            "И опять она заплакала горче прежнего. Наташа приподняла ее, обняла и, улыбаясь сквозь слезы, стала ее успокоивать.\n" +
            "— Соня, ты не верь ей, душенька, не верь. Помнишь, как мы все втроем говорили с Николенькой в диванной; помнишь, после ужина? Ведь мы все решили, как будет. Я уже не помню как, но помнишь, как было все хорошо и все можно. Вот дяденьки Шиншина брат женат же на двоюродной сестре, а мы ведь троюродные. И Борис говорил, что это очень можно. Ты знаешь, я ему все сказала. А он такой умный и такой хороший, — говорила Наташа... — ты, Соня, не плачь, голубчик милый, душенька, Соня. — И она целовала ее смеясь. — Вера злая, Бог с ней! А все будет хорошо, и маменьке она не скажет; Николенька сам скажет, и он и не думал об Жюли.\n" +
            "И она целовала ее в голову. Соня приподнялась, и котеночек оживился, глазки заблистали, и он готов был, казалось, вот-вот взмахнуть хвостом, вспрыгнуть на мягкие лапки и опять заиграть с клубком, как ему и было прилично.\n" +
            "— Ты думаешь? Право? Ей-богу? — сказала она, быстро оправляя платье и прическу.\n" +
            "— Право! ей-богу! — отвечала Наташа, оправляя своему другу под косой выбившуюся прядь жестких волос.\n" +
            "И они обе засмеялись.\n" +
            "— Ну, пойдем петь «Ключ».\n" +
            "— Пойдем.\n" +
            "— А знаешь, этот толстый Пьер, что против меня сидел, такой смешной! — сказала вдруг Наташа, останавливаясь. — Мне очень весело!\n" +
            "И Наташа побежала по коридору.";


    public static final String ANGRY = "";
}
